--SEEING CURRENT ROLE

SELECT current_role();

--SEEING ROLES OF CURRENT ROLE

SHOW GRANTS TO ROLE PUBLIC;

--CREATING BASIC ROLE

CREATE ROLE BASIC_ROLE;

--GRANTING PRIVERALEGES TO USE DB BUT NOT MODIFY

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE BASIC_ROLE;

GRANT USAGE ON DATABASE SALES_DB TO ROLE BASIC_ROLE;

GRANT USAGE ON SCHEMA SALES_DB.PUBLIC TO ROLE BASIC_ROLE;

GRANT SELECT ON TABLE SALES_DB.PUBLIC.IOWA_SALES TO ROLE BASIC_ROLE;

--SHOWING ROLES 
SHOW GRANTS TO ROLE BASIC_ROLE;

SHOW GRANTS TO ROLE SYSADMIN;

GRANT ROLE BASIC_ROLE TO ROLE SYSADMIN;
