SELECT * FROM IOWA_SALES; 

SELECT * FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_NAME = 'IOWA_SALES';

--CREATING CLUSTERS
ALTER TABLE IOWA_SALES CLUSTER BY(COUNTY);

SELECT * FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_NAME = 'IOWA_SALES';

--CLONE TABLE

CREATE OR REPLACE TABLE IOWA_SALES_CLUSTERED CLONE IOWA_SALES;

--LOOK AT CLONED TABLE

SELECT * FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_NAME = 'IOWA_SALES_CLUSTERED';

SELECT * FROM IOWA_SALES_CLUSTERED
WHERE COUNTY = 'CLINTON';

--REMOVE CLUSTERING ON FIRST TABLE TO COMPARE SPEED
--UNCLUSTERED EXECUTED IN 800MS
ALTER TABLE IOWA_SALES DROP CLUSTERING KEY;

SELECT * FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_NAME = 'IOWA_SALES';


--CLUSTERED EXECUTED IN 600MS
SELECT * FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_NAME = 'IOWA_SALES_CLUSTERED';



--EXAMINING WHICH COLUMN TO CLUSTER WITH JSON
--DATE COLUMN HAS TOO HGIH CARDINALITY 

SELECT SYSTEM$CLUSTERING_INFORMATION('IOWA_SALES', '(DATE)');

--CHECKING CITY COLUMN
--'CITY' COLUMN HAS HIGH CARDINALITY WHICH WOULD CAUSE EXPENSIVE RE-CLUSTERING

SELECT SYSTEM$CLUSTERING_INFORMATION('IOWA_SALES', '(CITY)');

--CHECKING COUNTRY COLUMN
--HAS SLIGHTLY LOWER CARDINALITY AND DEPTH

SELECT SYSTEM$CLUSTERING_INFORMATION('IOWA_SALES', '(COUNTY)');




