CREATE DATABASE WALMART_DB;

USE DATABASE WALMART_DB;

SELECT current_warehouse(), current_database(), current_schema();

---CREATE PERMANENT TABLE

CREATE OR REPLACE TABLE IN_PRODUCTION
("BRAND" STRING,
"MODEL" STRING,
"COLOR" STRING,
"MEMORY" STRING,
"STORAGE" STRING,
"RATING" FLOAT, 
"LAUNCH_DATE" DATE);

--- PROPERTIES OF CREATED TABLES

SELECT TABLE_NAME,
    TABLE_TYPE,
    IS_TRANSIENT,
    RETENTION_TIME,
    AUTO_CLUSTERING_ON
FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME LIKE 'IN_PRODUCTION%';

--LET'S SET A TIME-TRAVEL REQUEST TO KEEP HISTORICAL DATA UP TO 7 DAYS

ALTER TABLE IN_PRODUCTION SET DATA_RETENTION_TIME_IN_DAYS = 7;

--CHECKING TABLE

SELECT TABLE_NAME, 
       TABLE_TYPE, 
       IS_TRANSIENT, 
       RETENTION_TIME, 
       AUTO_CLUSTERING_ON
FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME LIKE 'IN_%';


---INSERT INFORMATION

INSERT INTO IN_PRODUCTION VALUES
('OPPO', 'A53', 'Moonlight Black', '4 GB', '64 GB', 4.5, '2020-04-07'),
('OPPO', 'F17' ,'Red', '2 GB', '16 GB', 4.2, '2020-05-02'),
('Google Pixel', 'Quite Black', 'Black', '4 GB', '128 GB', 4.4, '2020-05-12'),
('IQOO','3', 'Quantum Silver', '8 GB', '128 GB', 4.4, '2020-09-27'),
('HTC', 'Wildfire X', 'Blue', '3 GB', '32 GB', 3.9, '2020-10-10'),
('LG', 'W11', 'Black', '3 GB', '32 GB', 4, '2020-04-01'),
('LG', 'Q Stylus+', 'Black', '4 GB', '64 GB', 4, '2020-04-30');

SELECT * FROM IN_BETA;

---LET'S CREATE A CLONE OF TRANSIENT TABLE FROM IN_BETA IN PRODUCTION WORKSHEET


CREATE OR REPLACE TABLE IN_BETA_CLONE CLONE IN_BETA;

---THAT THROWS AN ERROR, HAS TO BE CLONED TO A TEMP TABLE

CREATE OR REPLACE TEMPORARY TABLE BETA_TO_TESTING CLONE IN_BETA;




SELECT * FROM IN_PRODUCTION;


---GET QUERY ID FOR HISTORIACL PURPOSES

SELECT last_query_id(); 


--01abd84a-3200-ba13-0000-0002f5a6b00d

---LET'S DELETE OPPO BRAND

DELETE FROM IN_PRODUCTION WHERE BRAND = 'OPPO';

---SET GOOGLE PIXEL TO BE "GP"

UPDATE IN_PRODUCTION SET BRAND = 'GP' where BRAND = 'Google Pixel';

SELECT * FROM IN_PRODUCTION;

---LET'S QUERY THE HISTORICAL DATA

SELECT * FROM IN_PRODUCTION before(statement => '01abd84a-3200-ba13-0000-0002f5a6b00d');


---SHOW ONLY 5 RECORDS

SELECT * FROM IN_PRODUCTION AT (offset => -60 * 5);

---This should show 14 records

SELECT * FROM IN_PRODUCTION AT (offset => -60 * 20);


DROP TABLE IN_PRODUCTION;
SELECT * FROM IN_PRODUCTION;


# Can restore dropped tables when time-travel enabled

UNDROP TABLE IN_PRODUCTION;
SELECT * FROM IN_PRODUCTION ;



CREATE OR REPLACE TABLE ORDER_DETAILS
(ord_id          BIGINT PRIMARY KEY,
 prod_id         VARCHAR(10) REFERENCES PRODUCT_INFO(prod_id),
 cust_id         VARCHAR(10) REFERENCES CUSTOMER_DETAILS(cust_id),
 quantity        INT,
 discount        INT,
 date            DATE
);

SHOW TABLES;

