--Will create materialized view to optimize the time it takes to load the large dataset consisting of 1.6GB with sample dataset

CREATE OR REPLACE TABLE LINEITEM AS
SELECT * FROM
"SNOWFLAKE_SAMPLE_DATA"."TPCH_SF10"."LINEITEM";

SELECT * FROM LINEITEM LIMIT 10;

CREATE OR REPLACE VIEW HIGH_TAX_VIEW
AS
SELECT * FROM STORE WHERE L_TAX > 0.05;

--CREATE OPTIMIZED MATERIALIZED VIEW

CREATE OR REPLACE MATERIALIZED VIEW HIGH_TAX_VIEW_MATERIALIZED
AS
SELECT * FROM STORE WHERE L_TAX > 0.05;


SELECT * FROM HIGH_TAX_VIEW_SECURE_MATERIALIZED WHERE L_TAX > 0.06;

