--TURNING OFF CACHING

ALTER SESSION SET USE_CACHED_RESULT = FALSE;


--CREATING A NEW TABLE
--THIS TOOK 18 SECONDS

CREATE OR REPLACE TABLE IOWA_SALES_OPTIMIZED 
AS SELECT * FROM IOWA_SALES; 

--SHOW THE JSON FILE

SELECT system$estimate_search_optimization_costs('IOWA_SALES');

--NOW LET'S SEE THE TABLE
--THIS TOOK ABOUT 3 SECONDS

SHOW TABLES LIKE 'IOWA_SALES%';

ALTER TABLE IOWA_SALES_OPTIMIZED ADD SEARCH OPTIMIZATION;

--AFTER SEARCH OPTIMIZATION, THIS TOOK 108ms

SHOW TABLES LIKE 'IOWA_SALES%';

--NON-OPTIMIZED TOOK 2.5 SECONDS LONG

SELECT * FROM IOWA_SALES
WHERE SALES >= 500;

--OPTIMIZED
--THIS TOOK 1.5 SECONDS
SELECT * FROM IOWA_SALES_OPTIMIZED
WHERE SALES >= 500;


--LET'S SEE OTHER EXAMPLES

SELECT * FROM "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF100"."ORDERS" LIMIT 10;

--CREATING TABLES
CREATE OR REPLACE TABLE ORDERS_CLUSTERED
AS SELECT * FROM "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF100"."ORDERS";

CREATE OR REPLACE TABLE ORDERS_SEARCH_OPTIMIZED
AS SELECT * FROM "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF100"."ORDERS";

--ADD SEARCH OPTIMIZATION AND CLUSTERING

ALTER TABLE ORDERS_CLUSTERED CLUSTER BY (O_CUSTKEY);

ALTER TABLE ORDERS_SEARCH_OPTIMIZED ADD search optimization;

SHOW TABLES LIKE 'ORDER%';

--LET'S START QUERYING
--THE SEARCH-OPTIMIZED TABLE TOOK 17 seconds

SELECT * FROM "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF100"."ORDERS"
WHERE O_CUSTKEY > 11004176 AND O_CUSTKEY < 13004176; 

--TRY THE CLUSTERED TABLE
--THE CLUSTERED TABLE TOOK 14 SECOMDS
SELECT * FROM ORDERS_CLUSTERED
WHERE O_CUSTKEY > 11004176 AND O_CUSTKEY < 13004176; 
