USE DATABASE WALMART_DB;

CREATE OR REPLACE TABLE IN_TESTING
("BRAND" STRING,
"MODEL" STRING,
"COLOR" STRING,
"MEMORY" STRING,
"STORAGE" STRING,
"RATING" FLOAT, 
"LAUNCH_DATE" DATE);


SELECT TABLE_NAME, 
        TABLE_TYPE, 
        IS_TRANSIENT, 
        RETENTION_TIME, 
        AUTO_CLUSTERING_ON
FROM INFORMATION_SCHEMA.TABLES  
WHERE TABLE_NAME LIKE 'IN_%';

INSERT INTO IN_TESTING VALUES
('OPPO', 'A12', 'Moonlight Black', '4 GB', '32 GB', 3.8, '2020-04-06'),
('ASUS', 'Zenfone Go' ,'Black', '4 GB', '64 GB', 3.9, '2020-05-01'),
('realme','C20', 'Cool Grey', '6 GB', '128 GB', 4.1, '2020-09-23'),
('HTC', 'Wildfire X', 'Blue', '3 GB', '32 GB', 3.9, '2020-10-02'),
('LG', 'W31', 'Black', '6 GB', '128 GB', 3.5, '2020-03-28');

SELECT * FROM IN_TESTING;

SELECT * FROM IN_PRODUCTION;



